import { existsSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { expect, test } from 'vitest'
import { SITE } from '../../scripts/build-site.mjs'
import { GUIDES } from './guides.ts'
import { PAGES, read } from './pages.ts'

const ld = (html: string) => [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(m => JSON.parse(m[1]))
const DATE = /^\d{4}-\d{2}-\d{2}$/

test('the hub: head, CollectionPage, breadcrumb, social image', () => {
  const html = read('guides.html')
  expect(html).toContain('<link rel="canonical" href="https://hourslip.dev/guides">')
  expect(html).toMatch(/<title>Guides[^<]*\| hourslip<\/title>/)
  const types = ld(html).map(x => x['@type'])
  expect(types).toEqual(['CollectionPage', 'BreadcrumbList'])
  expect(html).toContain('<meta property="og:image" content="https://hourslip.dev/og/guides.png">')
  expect(existsSync(join(SITE, 'og', 'guides.png'))).toBe(true)
})
test('every page footer links the hub', () => {
  for (const p of PAGES) expect(read(p), p).toContain('<a href="/guides">Guides</a>')
})
test('the hub lists exactly the guides, and each link resolves', () => {
  const hub = read('guides.html')
  const listed = [...hub.matchAll(/<li><a href="\/guides\/([a-z0-9-]+)">/g)].map(m => m[1])
  expect(listed.sort()).toEqual(GUIDES.map(g => g.slug).sort())
  for (const s of listed) expect(existsSync(join(SITE, 'guides', `${s}.html`)), s).toBe(true)
})
test('sitemap and llms.txt carry the hub and every guide', () => {
  const map = read('sitemap.xml'), llms = read('llms.txt')
  for (const loc of ['https://hourslip.dev/guides', ...GUIDES.map(g => `https://hourslip.dev/guides/${g.slug}`)]) {
    const m = new RegExp(`<url><loc>${loc}</loc><lastmod>([^<]+)</lastmod></url>`).exec(map)
    expect(m?.[1], loc).toMatch(DATE)
    expect(llms, loc).toContain(loc)
  }
  expect(llms).toContain('## Guides')
})
test.each(GUIDES.map(g => [g.slug, g.title]))('guide %s: head, TechArticle, dates, social image, limits, related', (slug, title) => {
  const html = read(`guides/${slug}.html`)
  expect(html).toContain(`<h1>${title}</h1>`)
  expect(html).toContain(`<link rel="canonical" href="https://hourslip.dev/guides/${slug}">`)
  const [article, crumbs] = ld(html)
  expect(article['@type']).toBe('TechArticle')
  expect(article.headline).toBe(title)
  expect(article.dateModified).toMatch(DATE)
  expect(html).toContain(`Last updated <time datetime="${article.dateModified}">`)
  expect(crumbs['@type']).toBe('BreadcrumbList')
  expect(crumbs.itemListElement.map((i: { item: string }) => i.item)).toEqual(['https://hourslip.dev/', 'https://hourslip.dev/guides', `https://hourslip.dev/guides/${slug}`])
  expect(html).toContain(`<meta property="og:image" content="https://hourslip.dev/og/${slug}.png">`)
  expect(existsSync(join(SITE, 'og', `${slug}.png`)), `og/${slug}.png`).toBe(true)
  expect(html).toContain('<h2 id="limits">What hourslip does not do</h2>')
  expect(html).toContain('<h2 id="related">Related</h2>')
  expect(html).toContain('<a href="/guides">All guides</a>')
  for (const m of html.matchAll(/href="(https?:[^"]+)"/g)) expect(m[1], slug).toMatch(/^https:\/\//)
})
test('guide figures: no local path, no client but the sample ACME', () => {
  for (const g of GUIDES) {
    const html = read(`guides/${g.slug}.html`)
    expect(html, g.slug).not.toMatch(/[A-Za-z]:\\|\/Users\/|\/home\/[a-z]|AppData|HOURSLIP_HOME=/)
  }
})
const imgs = () => PAGES.flatMap(p => [...read(p).matchAll(/<img [^>]*>/g)].map(m => ({ p, tag: m[0], src: / src="([^"]+)"/.exec(m[0])?.[1] ?? '' })))
test('every image on every page has alt, width and height, exists, and stays under 3 MB', () => {
  const all = imgs()
  expect(all.length).toBeGreaterThan(0)
  for (const { p, tag, src } of all) {
    expect(tag, p).toMatch(/ alt="[^"]{20,}"/)
    expect(tag, p).toMatch(/ width="[0-9]+" height="[0-9]+"/)
    expect(src, p).toMatch(/^\/[^/]/)
    const file = join(SITE, src.slice(1))
    expect(existsSync(file), src).toBe(true)
    expect(statSync(file).size, src).toBeLessThan(3 * 1024 * 1024)
  }
})
test('no media file is orphaned: every file in guides/media and every site GIF is referenced by a page (spec §6)', () => {
  const media = [...readdirSync(join(SITE, 'guides', 'media')).map(f => `/guides/media/${f}`), ...readdirSync(SITE).filter(f => f.endsWith('.gif')).map(f => `/${f}`)]
  const used = new Set(imgs().map(i => i.src))
  for (const m of media) expect(used.has(m), m).toBe(true)
})
test('no alt or caption says the client confirmed: a name is typed by whoever holds the link', () => {
  for (const p of PAGES) {
    const html = read(p)
    const texts = [...[...html.matchAll(/ alt="([^"]*)"/g)].map(m => m[1]), ...[...html.matchAll(/<figcaption>([^]*?)<\/figcaption>/g)].map(m => m[1])]
    for (const t of texts) expect(t, p).not.toMatch(/confirmed by the client|the client confirm/i)
  }
})
test('track-time-in-claude-code: the claims that would change if facts changed', () => {
  const html = read('guides/track-time-in-claude-code.html')
  // Claude Code's own numbers (code.claude.com, downloaded 2026-10-08)
  expect(html).toContain('href="https://code.claude.com/docs/en/commands"')
  expect(html).toContain('<code>/cost</code> as “Alias for <code>/usage</code>”')
  expect(html).toContain('href="https://code.claude.com/docs/en/costs#track-your-costs"')
  expect(html).toContain('Total duration (API):  6m 20s\nTotal duration (wall): 6h 33m 10s')
  expect(html).toContain('“These totals reset when <code>/clear</code> starts a new session”')
  expect(html).toContain('href="https://code.claude.com/docs/en/statusline#cost-and-duration-tracking"')
  expect(html).toContain("“Total wall-clock time the session has been running, in milliseconds. Accumulates across resumes and doesn't include time while the session isn't running”")
  expect(html).toContain('href="https://code.claude.com/docs/en/monitoring-usage#active-time-counter"')
  expect(html).toContain('“Tracks actual time spent actively using Claude Code, excluding idle time. This metric is incremented')
  expect(html).toContain('href="https://code.claude.com/docs/en/claude-directory#application-data"')
  expect(html).toContain("“Every prompt you've typed, with timestamp and project path.”")
  expect(html).toContain('href="https://code.claude.com/docs/en/data-usage"')
  expect(html).toContain('for 30 days by default')
  // WakaTime's own README (downloaded 2026-10-08)
  expect(html).toContain('href="https://github.com/wakatime/claude-code-wakatime"')
  expect(html).toContain('“Track your AI usage, lines of code generated, time spent prompting AI, etc. using the WakaTime plugin for Claude Code.”')
  // hourslip's counting rules (plugin/hooks/core/types.ts:68-70, presence.ts)
  expect(html).toMatch(/10-minute/)
  expect(html).toContain('more than 45 minutes')
  expect(html).toContain('not seen unless')
  // the captured week (spike 2026-10-08, run 2)
  expect(html).toContain('Thu 10-08  ACME Corp 0h40 (Claude 0h00)')
  // plugin 0.2.2 redraws the status line after each /hourslip command (spike 2026-10-08, run 3)
  expect(html).toContain('<div class="term-status">⏱ ACME Corp · ACME-182 · 0h40 today</div>')
  expect(html).toContain('Captured in Claude Code 2.1.293 on Windows, 2026-10-08, with a sample client (hourslip 0.2.2). The status line read 0h40 as soon as the 30 minutes were added, before the next prompt.')
  expect(html).not.toContain('still read 0h10')
  // README.md:3-4 and 126-127, in the README's words; dates checked
  expect(html).toContain('hourslip is a Claude Code mod (a plugin of function hooks)')
  expect(html).toContain('A session where an organization policy disables mods records nothing.')
  expect(html).toContain('<a href="https://wakatime.com/claude-code">WakaTime page for Claude Code</a> (checked 2026-10-08)')
  expect(html).toContain('Claude Code docs checked 2026-10-08.')
})
test('bill-clients-for-claude-code-hours: the claims that would change if facts changed', () => {
  const html = read('guides/bill-clients-for-claude-code-hours.html')
  // Claude Code's own numbers (code.claude.com, downloaded 2026-10-08)
  expect(html).toContain('href="https://code.claude.com/docs/en/costs#track-your-costs"')
  expect(html).toContain('Total duration (API):  6m 20s\nTotal duration (wall): 6h 33m 10s')
  expect(html).toContain('“These totals reset when <code>/clear</code> starts a new session”')
  expect(html).toContain('“The figure is an estimate”')
  expect(html).toContain('href="https://code.claude.com/docs/en/statusline#cost-and-duration-tracking"')
  expect(html).toContain('“Total time spent waiting for API responses in milliseconds”')
  expect(html).toContain('href="https://code.claude.com/docs/en/monitoring-usage#active-time-counter"')
  expect(html).toContain('“Tracks actual time spent actively using Claude Code, excluding idle time.”')
  // hourslip: billable = measured + by hand (core/summary.ts:6, snapshot.ts:40); invoice (snapshot.ts:42-45)
  expect(html).toContain('Billable is measured time plus time added by hand')
  expect(html).toContain('<code>ACME-2026-10</code>')
  expect(html).toContain('15 days after the last day of the month')
  expect(html).toContain('no advice on rates, tax or contracts')
  expect(html).toContain('“hourslip does not verify who confirms: anyone with the link can.”')
  // the captured publish summary (spike 2026-10-08)
  expect(html).toContain('Invoice ACME-2026-10: 66.67 USD, due 2026-11-15')
  expect(html).toContain('Billable 1h40 (measured 0h10, by hand 1h30) · Claude 0h00')
  expect(html).toContain('href="/guides/track-time-in-claude-code"')
  // the /usage block is trimmed from the costs page's; the commit-titles note (io/report-data.ts:32, io/commands.ts:124)
  expect(html).toContain('starts like this:')
  expect(html).toContain("the preview and the command's reply say they are unavailable")
  expect(html).toContain('Claude Code docs checked 2026-10-08.')
})
test('timesheet-per-ticket-from-branch: the claims that would change if facts changed', () => {
  const html = read('guides/timesheet-per-ticket-from-branch.html')
  // Jira's and Linear's own branch-naming docs (downloaded 2026-10-08)
  expect(html).toContain('href="https://support.atlassian.com/jira-software-cloud/docs/reference-issues-in-your-development-work/"')
  expect(html).toContain('“Include the work item key in the branch name when you create the branch to link it to your Jira work item.”')
  expect(html).toContain('git checkout -b JRA-123-&lt;branch-name&gt;')
  expect(html).toContain('“If you create a branch this way, the key is automatically added to the name of the branch.”')
  expect(html).toContain('href="https://linear.app/docs/github#branch-name"')
  expect(html).toContain('“Include issue ID in the branch name.”')
  expect(html).toContain('“If your branch name includes a Linear issue ID, Linear will automatically link the pull request to that issue.”')
  expect(html).toContain('href="https://support.atlassian.com/jira-software-cloud/docs/log-time-on-an-issue/"')
  expect(html).toContain('“Once you start work on a work item, log time to keep a record.”')
  expect(html).toContain('href="https://code.claude.com/docs/en/statusline#git-status-with-colors"')
  expect(html).toContain('BRANCH=$(git branch --show-current 2&gt;/dev/null)')
  // hourslip: the default pattern (core/types.ts:72), first match, case kept (core/rules.ts:93-98)
  expect(html).toContain('<code>[A-Z][A-Z0-9]+-T?\\d+</code>')
  expect(html).toContain('the first match')
  expect(html).toContain('“No ticket”')
  // the captured runs (spike 2026-10-08)
  expect(html).toContain('⏱ ACME Corp · ACME-182 · 0h10 today')
  expect(html).toContain('⏱ ACME Corp · 0h10 today')
  expect(html).toContain('⏱ ACME Corp · acme-190 · 0h41 today')
  expect(html).toContain('Tagged this session from now: ACME Corp · ACME-201.')
  expect(html).toContain('2026-10-08,ACME Corp,,0.08,0.00,0.00,')
  expect(html).toContain('ACME-201.</code> (captured with <code>claude -p</code> in Claude Code 2.1.292, 2026-10-08)')
  expect(html).toContain('0h41 today</code> (captured with <code>claude -p</code> in Claude Code 2.1.292, 2026-10-08; the 0h41 includes 30 minutes added by hand on ACME-190 that day)')
  // Jira's condition for creating the branch from the work item; dates checked
  expect(html).toContain('“If you’re using Bitbucket Cloud, GitHub or GitLab, you can create a branch directly from your Jira work item.”')
  expect(html).toContain('status line docs</a> (checked 2026-10-08)')
  expect(html).toContain('Branch format</a> (checked 2026-10-08)')
  expect(html).toContain('Claude Code docs checked 2026-10-08.')
  expect(html).toContain("the preview and the command's reply say they are unavailable")
  expect(html).toContain('src="/guides/media/timesheet-per-ticket-from-branch.gif"')
  // the GIF's ⚠ prefix, as seen in the recording (spike 2026-10-08); the redraw after a command (register.tsx command.run)
  expect(html).toContain("Recorded in Claude Code 2.1.293 on Windows, 2026-10-08, with a sample client and a local test server; the welcome banner is cropped. In this recording, Claude Code draws a plugin's status line with ⚠ and the plugin's name.")
  expect(html).toContain('It is redrawn when you send a prompt and when a turn starts or ends, and after each <code>/hourslip</code> command')
  expect(html).toContain('href="/guides/track-time-in-claude-code"')
  expect(html).toContain('href="/guides/bill-clients-for-claude-code-hours"')
})
test('send-client-timesheet-to-confirm: the claims that would change if facts changed', () => {
  const html = read('guides/send-client-timesheet-to-confirm.html')
  // Google's own help pages (downloaded 2026-10-08)
  expect(html).toContain('href="https://support.google.com/docs/answer/40608?hl=en"')
  expect(html).toContain('“You can import a spreadsheet in many file formats”')
  expect(html).toContain('href="https://support.google.com/chrome/answer/1069693?hl=en"')
  expect(html).toContain('“In the window that appears, select the destination and change your preferred print settings.”')
  expect(html).toContain('with the Save to Google Drive extension, choose “Save to Google Drive” as the destination; with Drive for desktop or the Drive website, click <em>Save as PDF</em>, then upload the PDF.')
  expect(html).toContain('href="https://support.google.com/drive/answer/2494822?hl=en"')
  expect(html).toContain('“you can control whether people can edit, comment on, or only open the file.”')
  expect(html).toContain('href="https://support.google.com/docs/answer/65129?hl=en"')
  expect(html).toContain('“Highlight the text, images, cells, slides, or scenes you want to comment on.”')
  // Confirm: a name typed by whoever holds the link (site/llms.txt:12, core/report.ts:7,45)
  expect(html).toContain('“hourslip does not verify who confirms: anyone with the link can.”')
  expect(html).toContain('whoever holds the link')
  expect(html).toContain('Confirmed by Dana Client (link holder) at 2026-10-07 18:06 UTC.')
  // the server writes UTC (server/src/services/page.service.ts:26); no host zone on the page
  expect(html).toContain('The server writes the time in UTC, as the line shows.')
  expect(html).not.toMatch(/UTC\+07:00/)
  expect(html).toContain('✓ confirmed by Dana Client (link holder, unverified)')
  // server: one confirm per version, the 410 page, the free limit (page.service.ts:31,68; reports.service.ts:37)
  expect(html).toContain('“This version was already confirmed. Nothing was changed.”')
  expect(html).toContain('the link now answers 410')
  expect(html).toContain('“This report is no longer available. It was removed by its author or reached the end of its two years.”')
  expect(html).toContain('unpublishing one does not give it back')
  expect(html).toContain('“This key has used its 2 free reports. Run /hourslip subscribe to publish more. Links you already sent keep working.”')
  expect(html).toContain('stays online for 2 years')
  // the captures (spike 2026-10-08)
  expect(html).toContain('src="/guides/media/send-client-timesheet-to-confirm.gif"')
  expect(html).toContain("the tip and spinner words are Claude Code's. In this recording, Claude Code draws a plugin's status line with ⚠ and the plugin's name.")
  expect(html).toContain('src="/guides/media/send-client-timesheet-to-confirm-report.png"')
  expect(html).toContain('href="/guides/bill-clients-for-claude-code-hours"')
  expect(html).toContain('href="/guides/track-time-in-claude-code"')
  expect(html).toContain('href="/guides/timesheet-per-ticket-from-branch"')
})
test('claude-code-time-trackers: the claims that would change if facts changed', () => {
  const html = read('guides/claude-code-time-trackers.html')
  // every row of the table has its source and the date checked
  const table = html.slice(html.indexOf('<table'), html.indexOf('</table>'))
  const rows = [...table.matchAll(/<tr>[\s\S]*?<\/tr>/g)].map(m => m[0]).slice(1)
  expect(rows.length).toBe(6)
  for (const r of rows) expect(r).toMatch(/href="https:\/\/[^"]+"[\s\S]*\(checked 2026-10-08\)/)
  // Claude Code's own numbers and MCP (code.claude.com, downloaded 2026-10-08)
  expect(html).toContain('href="https://code.claude.com/docs/en/costs#track-your-costs"')
  expect(html).toContain('“These totals reset when <code>/clear</code> starts a new session”')
  expect(html).toContain('<code>Total cost:            $0.55</code>')
  expect(html).toContain('href="https://code.claude.com/docs/en/mcp"')
  // WakaTime: its plugin's README, hooks and pages
  expect(html).toContain('href="https://github.com/wakatime/claude-code-wakatime"')
  expect(html).toContain('“Track your AI usage, lines of code generated, time spent prompting AI, etc. using the WakaTime plugin for Claude Code.”')
  expect(html).toContain('href="https://github.com/wakatime/claude-code-wakatime/blob/main/hooks/hooks.json"')
  expect(html).toContain('“WakaTime plugins collect file path and project names from your IDE.”')
  expect(html).toContain('href="https://wakatime.com/plugins"')
  expect(html).toContain('“1 week of dashboard history”')
  expect(html).toContain('WakaTime covers your editors and browsers')
  expect(html).not.toMatch(/a meeting or a browser/)
  // Toggl: its MCP server's README and docs
  expect(html).toContain('href="https://www.npmjs.com/package/@togglhq/mcp"')
  expect(html).toContain('“Works with any MCP client including Claude Code and Claude Desktop.”')
  expect(html).toContain('claude mcp add toggl-focus -- npx @togglhq/mcp')
  expect(html).toContain('href="https://docs.toggl.com/toggl-mcp-and-cl"')
  expect(html).toContain('“Information and guides for using Toggl on desktop, mobile, and browser extensions.”')
  // Harvest: its MCP help article
  expect(html).toContain('href="https://support.getharvest.com/hc/en-us/articles/46293697226381-Harvest-MCP"')
  expect(html).toContain('claude mcp add --transport http harvest --scope user https://api.harvestapp.com/mcp')
  expect(html).toContain('“reviewing and sending an invoice always happens in Harvest itself.”')
  expect(html).toContain("“Whether you can view another teammate's time depends on your role.”")
  expect(html).toContain("(others' time as your Harvest role allows)")
  // ccusage: README and docs
  expect(html).toContain('href="https://github.com/ccusage/ccusage"')
  expect(html).toContain('“Analyze coding (agent) CLI token usage and costs from local data.”')
  expect(html).toContain('href="https://ccusage.com/guide/blocks-reports"')
  expect(html).toContain('“Lasts exactly 5 hours from start time”')
  // left out, and why
  expect(html).toContain('href="https://clockify.me/help/integrations-and-add-ons/use-clockify-mcp-server-to-connect-to-ai-agent"')
  expect(html).toContain('not yet released')
  // hourslip (README.md:3-6, 105-108; site/llms.txt:12)
  expect(html).toContain('no tokens and no cost')
  expect(html).toContain('“hourslip does not verify who confirms: anyone with the link can.”')
  expect(html).toContain('href="/guides/track-time-in-claude-code"')
  expect(html).toContain('href="/guides/bill-clients-for-claude-code-hours"')
  expect(html).toContain('href="/guides/timesheet-per-ticket-from-branch"')
  expect(html).toContain('href="/guides/send-client-timesheet-to-confirm"')
})
